language: generic
os: linux
dist: xenial

jobs:
  include:
    - &gcc-7
      compiler: gcc
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ g++-7 ]
      env:
        - CXX=g++-7

    - &gcc-8
      compiler: gcc
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ g++-8 ]
      env:
        - CXX=g++-8

    - &gcc-9
      compiler: gcc
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ g++-9 ]
      env:
        - CXX=g++-9

    - compiler: clang
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test, llvm-toolchain-xenial-5 ]
          packages: [ clang-5.0, g++-7 ]
      env:
        - CXX=clang++-5.0

    - compiler: clang
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test, llvm-toolchain-xenial-6 ]
          packages: [ clang-6.0, g++-7 ]
      env:
        - CXX=clang++-6.0

    - compiler: clang
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test, llvm-toolchain-xenial-7 ]
          packages: [ clang-7, g++-7 ]
      env:
        - CXX=clang++-7

    - compiler: clang
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test, llvm-toolchain-xenial-8 ]
          packages: [ clang-8, g++-8 ]
      env:
        - CXX=clang++-8

    - compiler: clang
      addons:
        apt:
          sources: &clang-9-sources
            - ubuntu-toolchain-r-test
            - sourceline: deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [ clang-9, g++-9 ]
      env:
        - CXX=clang++-9

    - &clang-10
      compiler: clang
      addons:
        apt:
          sources: &clang-10-sources
            - ubuntu-toolchain-r-test
            - sourceline: deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [ clang-10, g++-9 ]
      env:
        - CXX=clang++-10

    - <<: *clang-10
      env:
        - CXX=clang++-10
        - CPPFLAGS="-fms-extensions"

    - &osx
      os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - CXX=clang++

    - <<: *osx
      osx_image: xcode10.3

    - <<: *osx
      osx_image: xcode11.3

    - <<: *gcc-9
      env:
        - CXX=g++-9
        - CPPFLAGS="-fsanitize=undefined -fuse-ld=gold"

    - <<: *gcc-9
      env:
        - CXX=g++-9
        - CPPFLAGS="-fsanitize=address -fuse-ld=gold"

    - <<: *clang-10
      env:
        - CXX=clang++-10
        - CPPFLAGS="-fsanitize=undefined"

    - <<: *clang-10
      env:
        - CXX=clang++-10
        - CPPFLAGS="-fsanitize=address"

    - compiler: clang
      addons:
        apt:
          sources: *clang-10-sources
          packages: [ clang-tidy-10, g++-9 ]
      env:
        - CLANG_TIDY=clang-tidy-10
      script:
        - make -kj3 clang-tidy

    - compiler: clang
      addons:
        apt:
          sources: *clang-10-sources
          packages: [ clang-tools-10, g++-9 ]
      script:
        - scan-build-10 --use-c++=clang++-10 --status-bugs make -kj3

    - compiler: gcc
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ g++-9, valgrind ]
      env:
        - CXX=g++-9
        - SPECIAL=valgrind
      script:
        - make -kj3 valgrind

    - <<: *gcc-7
      env:
        - CXX=g++-7
        - CXXFLAGS="-O0 --coverage"
      before_script:
        - pip install --user cpp-coveralls
      script:
        - make -kj3 check
        - coveralls --gcov gcov-7 --gcov-options '\-lp' --exclude src --exclude include/tao/json/external

    - compiler: clang
      addons:
        apt:
          sources: *clang-9-sources
          packages: [ clang-format-9, g++-9 ]
      script:
        - clang-format-9 -i -style=file $(find . -name '[^.]*.[hc]pp')
        - git diff --exit-code

script:
  - $CXX --version
  - make -kj3
