version: '{branch}-{build}'

os: Visual Studio 2017

configuration: Release

branches:
  only:
    - master

init: []

build_script:
- md build-vc
- cd build-vc
- cmake -Wno-dev .. -G "Visual Studio 15 2017"
- cmake --build .

test_script:
- ctest -C Debug --output-on-failure

install: []
