name: Code Coverage

on: [push, pull_request]

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    env:
      CXX_FLAGS: "-coverage"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 2

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DTAOCPP_JSON_BUILD_EXAMPLES=OFF

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

    - working-directory: build/
      run: bash <(curl -s https://codecov.io/bash)
