name: Code Coverage

on: [push, pull_request]

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      env:
        CXX: "-coverage"
      run: cmake $GITHUB_WORKSPACE

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

    - working-directory: build/
      run: bash <(curl -s https://codecov.io/bash)
