name: Linux

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-7
          - g++-8
          - g++-9
          - g++-10
          - clang++-8
          - clang++-9
          - clang++-10
          #- clang++-11
        build_type: [Debug, Release]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-old:
    strategy:
      fail-fast: false
      matrix:
        clang: [5, 6, 7]
        build_type: [Debug, Release]

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: sudo apt-get-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-${{ matrix.clang }} main'
    - run: sudo apt-get update -q
    - run: sudo apt-get install -yq clang-${{ matrix.clang }}

    - run: cmake -E make_directory build

    - working-directory: build/
      env:
        CXX: clang++-${{ matrix.compiler }}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-clang-extra:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      env:
        CXX: clang++
        CXX_FLAGS: "-fms-extensions"
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
