name: Sanitizer

on: [push, pull_request]

jobs:
  sanitizer:
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++, clang++]
        sanitizer: [address, undefined]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      env:
        CXX: ${{ matrix.cxx }}
        CXX_FLAGS: "-fsanitize=${{ matrix.sanitizer }}"
      run: cmake $GITHUB_WORKSPACE

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
